### ISSUE TITLE
Code blocks are missing a bottom margin

### ISSUE THREAD

**Issue by raamdev** [websharks/s2clean#25]
Paragraph tags have a `bottom-margin: 10px`, but code blocks have no bottom margin. That throws the spacing off and leaves the text below code block looking weird:

---

![2015-02-13_20-05-50](https://cloud.githubusercontent.com/assets/53005/6197871/d2217b04-b3bb-11e4-8ce4-7a43fef62013.png)

---

`<code></code>` tags should get a `bottom-margin:10px` to match that of paragraph tags.

**Comment by jaswsinc** [comment]
Fixed. Thanks! I'll push this over to ZenCache.com shortly.

**Comment by jaswsinc** [comment]
Updated at ZenCache.com :-)

**Comment by raamdev** [comment]
Awesome. Thanks! Confirmed fixed. :-)

![2015-02-14_12-42-35](https://cloud.githubusercontent.com/assets/53005/6200451/f80e5bda-b446-11e4-8074-8e7852c17a53.png)
